const ADD_LOCALITY_TO_FIELD_SEARCH_PAGE = 'ADD_LOCALITY_TO_FIELD_SEARCH_PAGE';
const CHANGE_FIELD_SEARCH_PAGE = 'CHANGE_FIELD_SEARCH_PAGE';
const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';

export {
  ADD_LOCALITY_TO_FIELD_SEARCH_PAGE,
  CHANGE_FIELD_SEARCH_PAGE,
  GET_ALL_LOCATIONS,
};
