const ADD_LOCALITY_TO_FIELD_SEARCH_PAGE = 'ADD_LOCALITY_TO_FIELD_SEARCH_PAGE';
const CHANGE_FIELD_SEARCH_PAGE = 'CHANGE_FIELD_SEARCH_PAGE';
const ASYNC_GET_LOCATIONS = 'ASYNC_GET_LOCATIONS';

export {
  ADD_LOCALITY_TO_FIELD_SEARCH_PAGE,
  CHANGE_FIELD_SEARCH_PAGE,
  ASYNC_GET_LOCATIONS,
};
