const ADD_LOCALITY_TO_FIELD_SEARCH_PAGE = 'ADD_LOCALITY_TO_FIELD_SEARCH_PAGE';
const CHANGE_FIELD_SEARCH_PAGE = 'CHANGE_FIELD_SEARCH_PAGE';
const ASYNC_GET_LOCATIONS = 'ASYNC_GET_LOCATIONS';
const GET_PROPERTIES = 'GET_PROPERTIES';
const GET_PROPERTY_BY_ID = 'GET_PROPERTY_BY_ID';
const ADD_PROPERTY_TO_FAVOURITES = 'ADD_PROPERTY_TO_FAVOURITES';
const REMOVE_PROPERTY_TO_FAVOURITES = 'REMOVE_PROPERTY_TO_FAVOURITES';
const RESET_PROPERTIES = 'RESET_PROPERTIES';

export {
  ADD_LOCALITY_TO_FIELD_SEARCH_PAGE,
  CHANGE_FIELD_SEARCH_PAGE,
  ASYNC_GET_LOCATIONS, GET_PROPERTIES,
  GET_PROPERTY_BY_ID,
  ADD_PROPERTY_TO_FAVOURITES,
  REMOVE_PROPERTY_TO_FAVOURITES,
  RESET_PROPERTIES,
};
